id: 4532ccc045984963a6ec280c7bf37c7f
initial_creation_type: ocr
source_metadata:
  volumes:
    8d65f4a627694bfc8c2dea5a41fda72b:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: འཇིག་རྟེན་ལས་འདས་པའི་ཡན་ལག་བདུན་པའི་ཆོ་ག།
      total_pages: 1953
      volume_number: 27
